-- 各種テーブル削除
DROP TABLE IF EXISTS recipes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;

-- ユーザーテーブル
CREATE TABLE users
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(20),
   email VARCHAR(255),
   password VARCHAR(50)
);

--カテゴリーテーブル

CREATE TABLE categories
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(20)
);

-- レシピテーブル
CREATE TABLE recipes
(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   user_id INTEGER REFERENCES users(id),
   category_id INTEGER REFERENCES categories(id),
   name VARCHAR(50),
   recipe TEXT
);